version: '3.7'

services:

  sample:
    container_name: research-ufsc
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development